In [1]:
import pandas as pd

In [17]:
df = pd.DataFrame({ 
    'ExampleOneID': [1, 2, 3],
    'Date': ['01-01-2020', '02-01-2020', '03-01-2020']
})

In [18]:
df.head()

   ExampleOneID        Date
0             1  01-01-2020
1             2  02-01-2020
2             3  03-01-2020

In [19]:
df.to_csv('exampleone.csv', index=False)

In [27]:
dftwo = pd.DataFrame({ 

    'ExampleTwoID': [1, 2, 3],
    'ExampleOneID': [1, 2, 3],
    'SomeCategoryTypeID': ['A', 'B', 'C'],
    'SomeGroupID': ['G1', 'G2', 'G1'],
    'DateIn': ['01-01-2021', '02-01-2021', '03-01-2021'],
    'DateOut': ['01-06-2021', '02-06-2021', '03-06-2021'],
    'Hours' : [100, 150, 200]
})

In [28]:
dftwo.head()

,ExampleTwoID,ExampleOneID,SomeCategoryTypeID,SomeGroupID,DateIn,DateOut,Hours
0,1,1,A,G1,01-01-2021,01-06-2021,100
1,2,2,B,G2,02-01-2021,02-06-2021,150
2,3,3,C,G1,03-01-2021,03-06-2021,200

In [29]:
dftwo.to_csv('exampletwo.csv', index=False)

In [38]:
dfthree = pd.DataFrame({    
    'ExampleThreeID': [1, 2, 3],
    'ExampleTwoID': [1, 2, 3],
    'ExampleOneID': [1, 2, 3],
    'START_DATE_RAW': ['01-01-2022', '02-01-2022', '03-01-2022'],
    'END_DATE_RAW': ['10-01-2022', '11-01-2022', '12-01-2022'],
    'DATE_IN_RAW': ['05-01-2022', '06-01-2022', '07-01-2022'],
    'HOURS_RAW': [120, 180, 240]
})

In [39]:
dfthree.head()

,ExampleThreeID,ExampleTwoID,ExampleOneID,START_DATE_RAW,END_DATE_RAW,DATE_IN_RAW,HOURS_RAW
0,1,1,1,01-01-2022,10-01-2022,05-01-2022,120
1,2,2,2,02-01-2022,11-01-2022,06-01-2022,180
2,3,3,3,03-01-2022,12-01-2022,07-01-2022,240

In [40]:
dfthree.to_csv('examplethree.csv', index=False)

In [52]:
dffour = pd.DataFrame({    
    'ExampleFourID': ['CODE1', 'CODE2', 'CODE3'],
    'ExampleTwoID': [1, 2, 3],
    'YesOrNot': ['yes', 'no', 'yes']
})

In [53]:
dffour.head()

  ExampleFourID  ExampleTwoID YesOrNot
0         CODE1             1      yes
1         CODE2             2       no
2         CODE3             3      yes

In [54]:
dffour.to_csv('examplefour.csv', index=False)